[project]
name = "eye-disease-detection-system"
version = "0.1.0"
description = "Eye Disease Detection System"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "flask",
    "opencv-python-headless>=4.8.0,<5.0.0",
    "numpy",
    "pillow",
    "gunicorn"
]

[tool.vercel]
entrypoint = "app:app"
